### ISSUE TITLE
Reusing Action between different callers

### ISSUE THREAD

**Issue by Takitaf** [Mahmoudz/Porto#13]
Hello there. We've started to develop a new PHP project using the Porto pattern, which (in theory) is the 'answer on all of my questions'. Good job!

However, there is something I'm not sure how to deal with. Let's say we have an Action that do something like attaching roles to a specific user. We have a special route in our API, but also want to have a possibility to do this from console (SSH). And there is a problem: Action receives Request instance as parameter - and we won't create Request while using console.

4 possible solutions that came to my mind:

1. Let Action method receives simple array of data instead of Request, but it forces us to pick that data in Controller, when in API/Web request.
2. Create SubAction for every Action that we need to be usable from different sources (API, Console). SubActions can receive simple array as parameters.
3. Create variant of Action for every source. (duplication of code, makes Actions less reusable, list of use-cases are less readable)
4. Implement a different methods in Action (console, api), and call them from run() method, which choose the correct method by the type of parameter. (if parameter is Request - call 'api', if Console - call console).

I guess the best one is probably number 4, as all others have some drawbacks, but maybe You already had some thoughts in this case and have good solution?

**Comment by Mahmoudz** [comment]
@Takitaf thanks for your question, this is actually a real problem. In the early days of Apiato I used to pass data as parameters to the Action. However, while refactoring, I found that there's a lot of parameters being repeated over and over. So just to reduce that amount of code and due to the fact that we don't use as much Command as we use API requests (for this API project), I decided to pass the request itself to the Action, as a way to first pass objects instead of row data and second prevent these long parameters. 

My current solution, to your described problem is to try to call Tasks from Commands and Actions from Controllers. I know it may not be the best solution especially for different types of projects where they rely on Commands. I actually like the fourth option, but I think the different implementations for api, cli or web should be completely separated in different Actions because you might have different naming for the Action itself in each of these interfaces domain.

I guess the best thing to do, is to revert those parameters (means pass multiple inputs each one as it's own parameter `ActionDoSomething::run($name, $age, $location)`). This way if the same Actions should by the API and CLI interfaces, the API will read those values form the HTTP payload and pass them, and the CLI will maybe get them from the command parameters and pass them as well. Of course same apply for the Web interface.

Kindly let me know what you think, does it worth filling those Action parameters from Controllers in the right order and then using them from the Actions? Note you may want to pass some extra data sometimes such as some Request headers values or other type of data.

**Comment by Takitaf** [comment]
@Mahmoudz thanks for a response. I had a talk with one of my teammates just after I sent this question. After that I decided that the best way in my case is to simply make Action::run method receive multiple parameters instead of just Request. Of course, it makes our Controllers a little bit bigger, as they need to pick all necessary data from Request, but also makes Actions far more reusable.

Console was not the only problem, as I have also some Listeners here and there. It was second time when I wanted to call Action, this time from Listener, and again had the same problem - can't pass Request instance. 

Personally, I think that, if we move the 'picking data from request' part to Controllers for WEB and CLI, Actions will be as reusable as they only can be. If we ever find next 'Something' component, that could use Actions, there will be no problem with passing data. Of course, there can be a serious drawback with "Actions with one million parameters" issue, but I guess I prefer to have THAT kind of problem. :)

We're just at the beginning of first project with Porto. I'll give a try the "Action::run with multiple parameters" approach and check if it fits our need.

Anyway, whole pattern is very promising, so I'll probably come back here in near future with a bunch of new questions. :)

**Comment by Mahmoudz** [comment]
@Takitaf cool, already refactored the code. https://github.com/apiato/apiato/commit/0a0427b439171b9c1a1ced034d143b17f091c7ff

**Comment by Mahmoudz** [comment]
@Takitaf Hi again, I was thinking of that approach after I implemented it, and again it start feeling that pain on all these parameters, so I might refactor it again and replace those parameters with DTO (Data Transfer Objects). So instead of passing a Request you will build and pass a DTO. could be as simple as `new FooDataTransfer->fromRequest($FooRequest)` and this way from Commands or Tests you can pass those objects. What do you think of that approach?

**Comment by Takitaf** [comment]
@Mahmoudz Hello there.

We, again, had a talk with a friend of mine just after You closed this issue. We debated about "what to do if there will be finally action with reeaaaaly large amount of parameters". His idea was exactly what your proposal is - to create some kind of container class and put parameters into it.

I guess that's probably the best thing to do, as we can create that DTO from everywhere. Still, however, I don't have any Actions which would have more than 3 parameters for now, so it feels like a little bit overkill, but we will change to this approach anyway. That's probably the best solution, after all.
