### ISSUE TITLE
Middleware?

### ISSUE THREAD

**Issue by srlopez** [Mahmoudz/Porto#7]
Where you put the Middleware level in the picture of "_Typical Container Example_"?
One for container, or middleware for each API/WEB?
Thanks

Are you planning to provide some examples of this architecture, explaining the most adequate pattern or SOLID principle for each component?
Really good job.

**Comment by Mahmoudz** [comment]
@srlopez thanks for your message.

I would usually place my middleware's in the Ship layer because most of my middleware's are for the Application level. 

In your case, it depend. Cause I think of every component based on its use case. If this middleware is only for the API then would be better to be there in the UI/API folder. While if it's for the entire container usage, I'd put it in the container root. And when it's global of course in the Ship layer. 

If you have any recommendations or feedbacks I'm always open for improvements.
